Driver do Barômetro (MS5607)
zenitheesc/Drivers pull request #34
Opened 2022-01-25 19:42 UTC by GustavoKanaiama

Closes #33 

## What type of PR is this? (check all applicable)
- [x] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

# Testing

2022-01-25 19:44 UTC, leocelente commented
blz vou dar uma olhada :eyes:

2022-01-25 19:48 UTC, leocelente commented on MS5607/MS5607.c
> +int convert(int n) {
Colocar como `static`

2022-01-25 20:07 UTC, leocelente commented
Beleza, vamos reabrir essa joça

2022-02-09 15:06 UTC, mairacanal requested changes
Tenho alguns comentários gerais:

- O arquivo `.idea/vcs.xml` é desnecessário, por favor, apague-o, já que o VCS não está sendo usado com sistema de versionamento
- Utilize mensagens de commit mais específicas e em inglês
- Creio que a legibilidade do código, no geral, poderia melhorar:

Primeiro, separe as funções "privadas", tipo a get_PROM, das funções públicas. Isso facilita o trabalho do leitor do código.

Segundo, reveja a forma que você estruturou esse driver. Alguns códigos que estão muito bem estruturados: https://github.com/UravuLabs/MS5607 e https://github.com/Schm1tz1/arduino-ms5xxx

Algumas funções desse driver, como getAltitude e getTemperature, não foram desenvolvidas.

Por fim, reveja essa função `convert`, ela tem um custo de ordem `n`. Essas operações podem ser realizadas com complexidade constante, o que é interessante para um sistema embarcado.

OBS.: Todos os meus comentários dizem respeito a qualidade de código, então, sobre funcionalidade do driver, eu não faço a mínima ideia e isso é problema do @leocelente.

2022-02-10 01:48 UTC, Grillo-0 requested changes

2022-02-10 01:48 UTC, Grillo-0 commented on MS5607/MS5607.c
> +error_t ms5607_reset(ms5607_t ms5607) {
É necessário passar o argumento como ponteiro

2022-02-10 01:48 UTC, Grillo-0 commented on MS5607/MS5607.c
> +uint8_t get_Dconst(ms5607_t ms5607) {
É necessário passar o argumento como ponteiro

2022-02-10 01:48 UTC, Grillo-0 commented on MS5607/MS5607.c
> +uint8_t ms5607_init(ms5607_t ms5607, enum OSR_samples mode) {
É necessário passar o argumento como ponteiro

2022-02-10 01:48 UTC, Grillo-0 commented on MS5607/MS5607.c
> +int32_t ms5607_getPressure(ms5607_t ms5607) {
É necessário passar o argumento como ponteiro

2022-02-10 01:48 UTC, Grillo-0 commented on MS5607/MS5607.c
> +} //convert decimal to binary
Essa função não deve ser usada. Ela irá fazer uma conversão errônea, por exemplo:
convert(2) => 10 (dez)
convert(8) => 101 (cento e um)
convert(8) => 1000 (mil)
Ela apenas transforma um numero para outro, e não converte um numero de decimal para binário.

2022-02-14 17:56 UTC, mairacanal requested changes
Esse código ainda não compila e o arquivo `.idea/vcs.xml` ainda não foi deletado.

2022-02-14 17:56 UTC, mairacanal commented on MS5607/MS5607.c
> +                           &ms5607->prom.C4, &ms560->prom.C5,  &ms5607->prom.C6};
```suggestion
                           &ms5607->prom.C4, &ms5607->prom.C5,  &ms5607->prom.C6};
```

2022-02-14 17:56 UTC, mairacanal commented on MS5607/MS5607.c
> +    uint8_t mode = ms5607.OSR_mode;
```suggestion
    uint8_t mode = ms5607->OSR_mode;
```

2022-02-23 22:16 UTC, mairacanal requested changes
Esse código ainda não compila e o arquivo `.idea/vcs.xml` ainda não foi deletado.

2022-02-23 22:16 UTC, mairacanal commented on MS5607/MS5607.c
> +		uint8_t Command_D = (mode << 1) | vec_mask[i];
```suggestion
		uint8_t command_D = (mode << 1) | vec_mask[i];
```

2022-02-23 22:16 UTC, mairacanal commented on MS5607/MS5607.c
> +		uint8_t Command_D = (mode << 1) | vec_mask[i];
Tente adotar um padrão de formatação de variável

2022-02-23 22:16 UTC, mairacanal commented on MS5607/MS5607.h
> +#define QNT_DValue     ((uint8_t) (2))
```suggestion
#define QNT_DVALUE     ((uint8_t) (2))
```

2022-04-05 00:16 UTC, merged