Upload das bibliotecas do thermistor e do MAX6682
zenitheesc/Drivers pull request #40
Opened 2022-02-15 17:11 UTC by 18950

## Upload das bibliotes feitas
- [x ] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ x] 🚩 Other

# Changes:

Adicionei as bibliotecas já feitas o thermistor e o MAX6682, porém ainda falta terminar a documentação.

# Testing

2022-02-17 04:38 UTC, leocelente requested changes
O principal problema foi a confusão entre bits e bytes que chegam do sensor. Mas no geral falta estrutura no código. Os pontos principais estão presentes, mesmo que de forma quebrada. Mas senti falta de uma maneira de referenciar um sensor específico dentro do código, como uma `struct max6682`, pois vamos ter 3 sensores no sistema cada um com uma resistência diferente

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Inc/MAX6682.h
> +#define		Rext3	0.8765
Talvez um `enum` seja mais indicado

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Inc/MAX6682.h
> +float MAX6682_Getvalue(int bits,int Rext_select);
Nome não bate com o `.c`

2022-02-17 04:38 UTC, leocelente commented on MAX6682/README.md
> +
Documentação do Driver

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +#include "stm32l4xx_hal.h"
Drivers não devem depender diretamente da HAL, mas passar pelo `platform.h`

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +		} spi_device_t;
Essas definições estão na `platform.h`

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +		static uint16_t SPI_data[11];
Variável `static` vai ter seu valor mantido entre chamadas da função. Como essa variável é alterada dentro dessa função L38, isso implica que dois sensores compartilham essa memória. Pode causar problemas no futuro

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +		HAL_SPI_Receive(&MAX6682.spi, (uint8_t *)SPI_data, 11, 100);
Pelo que estou entendendo você está lendo 11 bytes, mas a saída do sensor são 11 **bits** então devem ser lidos apenas 2 bytes.

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +		HAL_GPIO_WritePin(GPIOx, GPIO_Pin, GPIO_PIN_SET);
Ver funções `gpio_*` e `spi_receive` do `platform.h`

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +		float LSB,temp=0;
Tenta rodar a formatação automática da CubeIDE, com `Ctrl`+`Shift`+`F` e remover linhas vazias.
LSB contém um valor aleatório (não está inicializado)

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +			switch(Rext_select){	//LSB value depends on the external resistence, read datasheet for more details
Mais detalhes no comentário, que parte do datasheet?

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +			}
Tem alguma razão para a variável `Rext_select` já não ser o valor de `LSB`?

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +			if (SPI_data[0]==1){				//temp neg
Consequência da confusão entre bits e bytes. Tem que checado o décimo primeiro bit.

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +			}
Essa seção de conversão entre binário e decimal será desnecessária.

2022-02-17 04:38 UTC, leocelente commented on MAX6682/Src/MAX6682.c
> +}
Por que o código da copiado e colado da função anterior? Por que não simplesmente chamar a função de conversão depois de ler os valores brutos? Ou por que não retornar o valor bruto de `GetValue`?

2022-02-17 04:38 UTC, leocelente commented on Termistor/Inc/thermistor.h
> +#include <inttypes.h>
tecnicamente correto, mas geralmente só utilizamos o `<stdint.h>` mesmo.

2022-02-17 04:38 UTC, leocelente commented on Termistor/Src/thermistor.c
> +	double 	raw;
Não é necessário uso de `double`

2022-02-17 04:38 UTC, leocelente commented on Termistor/Src/thermistor.c
> +	int		sample[sample_n], i;
O GCC até deixa você construir o array com tamanho variável `sample_n`, mas é recomendado que seja uma constante (`#define`)
Ambos o array e `i` não estão inicializados. E é mais indicado inicializar o `i` dentro do `for`

2022-02-17 04:38 UTC, leocelente commented on Termistor/Src/thermistor.c
> +			  HAL_Delay(10);
É melhor usar o módulo de ADC da `platform.h` 
O ADC é inicializado em toda iteração do loop.
Tem motivo para esse delay depois do poll?

2022-02-17 04:38 UTC, leocelente commented on Termistor/Src/thermistor.c
> +		  for (i=0; i< sample_n; i++) {
Por que o `i`é o mesmo para toda função o loop anterior vai ser quebrado.

2022-02-17 04:38 UTC, leocelente commented on Thermistor/README.md
> +
Documentação de como usar a biblioteca e como ela funciona, principalmente as referências sobre as equações

2022-02-17 14:31 UTC, mairacanal requested changes
Para além das considerações do Celente, eu recomendaria você ter um pouco mais de carinho com as mensagens de commit. Tente colocar mensagens descritivas sobre as modificações realizadas. Dicas de como fazer um bom commit: https://cbea.ms/git-commit/

Além disso, melhore a formatação e a qualidade do código. Há código repetido e, também, más práticas de código. Algumas referências para qualidade de código:
- https://becode.com.br/clean-code/
- https://github.com/mcinglis/c-style
- https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Inc/thermistor.h
> +#define INC_thermistor_H_
É boa prática colocar o guard em letra maiúscula

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Inc/thermistor.h
> +	#define a 4095			//resolution of the adc reading
Usualmente, o nome da variável definida pelo #define encontra-se em letra maiúscula, com o objetivo de facilitar a leitura do código.

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Inc/thermistor.h
> +uint16_t *ADC_init(void);
Essa função não está definida no source file

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Src/thermistor.c
> +#define SRC_thermistor_C_
Código fonte não precisa de guard, já que esse guard é utilizado no header file pelo preprocessador para não incluir multiplas vezes a mesma coisa.

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Src/thermistor.c
> +		  temp = temp - 273.15;
Isso pode ser escrito de forma mais legivel

2022-02-17 14:31 UTC, mairacanal commented on Termistor/Src/thermistor.c
> +		  temp = temp - 273.15;
Evite copiar e colar código. Use a função declarada acima.

2022-03-17 23:03 UTC, leocelente commented
Foram reiniciados os trabalhos deste driver e da biblioteca em separado, irei abrir outros dois PRs para cada parte.

2022-03-17 23:03 UTC, closed without merging